spring:
  application:
    name: hystrix-service

server:
  port: 9005

eureka:
  client:
    service-url:
      defaultZone: http://localhost:520/eureka/

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
