eureka:
  client:
    service-url:
      defaultZone: http://localhost:520/eureka/
spring:
  application:
    name: hystrix
server:
  port: 9001
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream